spring:
  datasource:
    url: jdbc:mysql://localhost/academia?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Banco@25
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true